// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://occhxidhzhupyhikdqlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jY2h4aWRoemh1cHloaWtkcWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjA1NDIsImV4cCI6MjA2ODIzNjU0Mn0._BErp32Q-OEQ-_l9PNXJE1f6EX2a05Noc57_aOB5_0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});